source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'
pod 'AFNetworking', '2.4.1'
pod 'Reachability', '>= 3.1.1'
pod 'SVProgressHUD', '>= 1.0'
pod 'FMDB', '>= 2.4'
pod 'NanoStore', '2.7.7'
pod 'EGOTableViewPullRefreshAndLoadMore', '1.0.4'
pod 'SDWebImage', '3.7.1'